version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run:
          name: Install dependency
          command: yarn
      - run:
          name: Run application
          command: adonis serve
      - run:
          name: Test
          command: yarn test

workflows:
  build_and_test:
    jobs:
      - test